import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Syne, Space_Grotesk } from "next/font/google";
// import "./globals.css";

// const syne = Syne({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800"],
//   variable: "--font-syne",
//   display: "swap",
// });

// const spaceGrotesk = Space_Grotesk({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-space",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "TECHNEO – Best Software Solution",
//   description:
//     "High-Performance Software Designed To Streamline Operations & Boost Productivity",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${syne.variable} ${spaceGrotesk.variable}`}>
//       <body className="antialiased font-[var(--font-space)] bg-[#050505] text-white selection:bg-[#9EFF00] selection:text-black">
//         {children}
//       </body>
//     </html>
//   );
// }