import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* META PIXEL */}
        <Script
          id="facebook-pixel"
          strategy="afterInteractive"
        >
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;
            n.push=n;
            n.loaded=!0;
            n.version='2.0';
            n.queue=[];
            t=b.createElement(e);
            t.async=!0;
            t.src=v;
            s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)
            }(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');

            fbq('init', '908482295567136');
            fbq('track', 'PageView');
          `}
        </Script>

        
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* NOSCRIPT */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{
              display: "none",
            }}
            src="https://www.facebook.com/tr?id=908482295567136&ev=PageView&noscript=1"
          />
        </noscript>
      </body>
    </html>
  );
}





// import type { Metadata } from "next";
// import { Syne, Space_Grotesk } from "next/font/google";
// import "./globals.css";

// const syne = Syne({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800"],
//   variable: "--font-syne",
//   display: "swap",
// });

// const spaceGrotesk = Space_Grotesk({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-space",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "TECHNEO – Best Software Solution",
//   description:
//     "High-Performance Software Designed To Streamline Operations & Boost Productivity",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${syne.variable} ${spaceGrotesk.variable}`}>
//       <body className="antialiased font-[var(--font-space)] bg-[#050505] text-white selection:bg-[#9EFF00] selection:text-black">
//         {children}
//       </body>
//     </html>
//   );
// }